# Generated by Django 5.2 on 2025-05-18 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_profile_age_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=375397777777, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+37529XXXXXXX'", regex='^\\+37529\\d{7}$')]),
            preserve_default=False,
        ),
    ]
