# Generated by Django 5.2 on 2025-05-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='providers',
            field=models.ManyToManyField(to='shop.provider'),
        ),
    ]
