# Generated by Django 5.2 on 2025-05-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='providers',
            field=models.ManyToManyField(related_name='provider_product', to='shop.provider'),
        ),
    ]
