# Generated by Django 5.2.6 on 2025-09-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_aboutcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
