# Generated by Django 5.2 on 2025-05-03 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='providers',
            field=models.ManyToManyField(related_name='provider_product', to='shop.provider'),
        ),
    ]
