# Generated by Django 5.2 on 2025-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_orderitem_price_at_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=20)),
                ('start_work', models.TimeField()),
                ('end_work', models.TimeField()),
            ],
        ),
    ]
