# Generated by Django 5.2.6 on 2025-09-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('video', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='img')),
                ('history', models.TextField()),
                ('requisites', models.TextField()),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
